Up toolkit version to 1.4
timescale/timescaledb-docker-ha pull request #182
Opened 2021-11-17 22:21 UTC by JLockerman

This version enables Toolkit to work on pg14

2021-11-18 23:09 UTC, WireBaron approved these changes

2021-11-19 07:12 UTC, feikesteenbergen approved these changes
We could also create a Make target that does what it should do managed by the toolkit extension itself?

2021-11-23 07:46 UTC, feikesteenbergen requested changes

2021-11-23 07:46 UTC, feikesteenbergen commented on Dockerfile
> +                    && git clean -e target -f -x \
From [GH Actions](https://github.com/timescale/timescaledb-docker-ha/runs/4268475658?check_suite_focus=true):

> fatal: destination path '/build/timescaledb-toolkit' already exists and is not an empty directory.

2021-11-24 20:43 UTC, feikesteenbergen approved these changes

2021-11-30 11:11 UTC, merged